"""
Django settings for lumivis project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-98ixpsnk22dbu3u*7c7x(l0+isy13iv6om0!na8q%6wh5i6zv6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [ '.samanyastra.com', "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'rest_framework',
    'rest_framework.authtoken',
    'messaging',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '300/minute',
        'auth': '10/minute',
    },
    'EXCEPTION_HANDLER': 'products.api_utils.custom_exception_handler',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lumivis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.cart',
                'products.context_processors.order_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'lumivis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE":   "django.db.backends.postgresql",
        "NAME":     env("DB_NAME",     default=""),
        "USER":     env("DB_USER",     default=""),
        "PASSWORD": env("DB_PASSWORD", default=""),
        "HOST":     env("DB_HOST",     default=""),
        "PORT":     env("DB_PORT",     default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'products' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "products.storage_backends.AzureMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "products.storage_backends.AzureStaticStorage",
    },
}

MEDIA_URL = '/media/'

# Azure Blob Storage — media and static files both live here, but a blob URL
# is never handed to a client. Every file is streamed through our own proxy
# views instead (products.views.serve_media / serve_static) — see
# products/storage_backends.py. Nothing is ever written to local/pod disk,
# so replicas and restarts stay stateless.
# Container 'lumivis', with blobs namespaced under 'media/' and 'static/'
# virtual dirs respectively.
AZURE_CONNECTION_STRING = env('AZURE_CONNECTION_STRING', default='')
AZURE_ACCOUNT_NAME = env('AZURE_ACCOUNT_NAME', default='')
AZURE_ACCOUNT_KEY = env('AZURE_ACCOUNT_KEY', default='')
AZURE_CONTAINER = env('AZURE_CONTAINER', default='lumivis')
AZURE_MEDIA_PREFIX = env('AZURE_MEDIA_PREFIX', default='media')
AZURE_STATIC_PREFIX = env('AZURE_STATIC_PREFIX', default='static')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# CSRF — ensure cookie is always accessible and never requires HTTPS in dev
CSRF_COOKIE_HTTPONLY  = False   # must be readable by the browser
CSRF_COOKIE_SAMESITE  = 'Lax'  # send cookie on same-site navigations (default, explicit)
CSRF_COOKIE_SECURE    = False   # allow HTTP in development

CSRF_TRUSTED_ORIGINS = ['https://*.samanyastra.com']

# ── Samanyastra messaging (django-messaging) ────────────────────────────────
# Mail identity
DEFAULT_FROM_MAIL = env('DEFAULT_FROM_MAIL', default='noreply@samanyastra.com')
SUPPORT_LINK = env('SUPPORT_LINK', default='https://samanyastra.com/support')

# Used to build absolute URLs (e.g. the reset link, a logo <img> src) in
# emails, which render outside any request and can't resolve a relative path.
SITE_BASE_URL = env('SITE_BASE_URL', default='http://localhost:8000')

# Standalone mail-sending REST service (outlook_mailer) — it owns delivery,
# this app only makes one synchronous POST per recipient.
MAIL_SERVICE_URL = env('MAIL_SERVER_HOST', default='')
MAIL_SERVICE_APP_ID = env('MAIL_SERVICE_APP_ID', default='')
MAIL_SERVICE_APP_SECRET = env('MAIL_SERVICE_APP_SECRET', default='')

PASSWORD_RESET_TIMEOUT = 60 * 60  # 1 hour, in seconds
