# Generated by Django 6.0.6 on 2026-06-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_wishlist_transaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transctions',
        ),
    ]
