# Generated by Django 6.0.6 on 2026-07-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_cancelrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('badge_text', models.CharField(default='Limited Offer', max_length=50)),
                ('discount_text', models.CharField(default='40% OFF', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popup_offers', to='products.product')),
            ],
            options={
                'verbose_name': 'Popup Offer',
            },
        ),
    ]
