# Generated by Django 6.0.6 on 2026-07-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_popupoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(default='inside', max_length=20),
        ),
    ]
