# Generated by Django 6.0.6 on 2026-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
