# Generated by Django 6.0.6 on 2026-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_seed_lumivis_forgot_password_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelrequest',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelrequest',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
